### ISSUE TITLE
No fixtures are generated / No doc on how to make them ourselves

### ISSUE THREAD

**Issue by sitarane** [shioyama/mobility#626]
When setting up Mobility, many existing tests will be rendered failing as there aren't translations in the existing fixtures.

Expected: when installing Mobility, some fixture scaffolds are created. At least with dummy content.

If that can't be done, at the very least there should be a doc section about what a translated fixture should look like.

**Comment by shioyama** [comment]
I'm happy to accept a PR for the doc addition, but not implementing new functionality.

**Comment by dvodvo** [comment]
The rails documentation says scant little [about testing or fixtures](https://guides.rubyonrails.org/i18n.html).

I have seen different apporaches suggested. 

- under fixtures, have a directory with the class name and inside it a translations.yml file
- having a mobility/string_translations.yml (and sister text_translation) set up.
The latter feels more natural, as it reflects the database structure.

Yet, for a given class
```
class Promotion < ApplicationRecord
  extend Mobility

  translates :description_public, type: :text
```

a fixture, with stock scaffold generation, for promotions.yml
```
full:
  description_internal: MyText
  description_public: MyText
```
and a mobility/text_translations.yml with
```
promo_full:
  translatable_id: promotions(:full).id
  translatable_type: "Promotion"
  key: "description_public"
  value: "full_full"
  locale: "en"
  created_at: <%= Time.now %>
  updated_at: <%= Time.now %>
```
when intercepted in a test
```
puts promotions(:full).description_public_en.inspect
puts promotions(:full).description_public.inspect
```
yields nil for both.

So this is an issue (for which, admittedly Rails doc does not help).   
To which I might attempt a documentation PR... However, I still do not see how to resolve the Minitest fixture issue.
