### ISSUE TITLE
Testing and fixtures

### ISSUE THREAD

**Issue by dvodvo** [shioyama/mobility#644]
The rails documentation says scant little, to this day, about testing or fixtures  
https://guides.rubyonrails.org/i18n.html.

I have seen different apporaches suggested. 

- under fixtures, have a directory with the class name and inside it a translations.yml file
- having a mobility/string_translations.yml (and sister text_translation) set up.
The latter feels more natural, as it reflects the database structure.

Yet, for a given class
```
class Promotion < ApplicationRecord
  extend Mobility

  translates :description_public, type: :text
```

a fixture, with stock scaffold generation, for promotions.yml
```
full:
  description_internal: MyText
  description_public: MyText
```
and a mobility/text_translations.yml with
```
promo_full:
  translatable_id: promotions(:full).id
  translatable_type: "Promotion"
  key: "description_public"
  value: "full_full"
  locale: "en"
  created_at: <%= Time.now %>
  updated_at: <%= Time.now %>
```
when intercepted in a test
```
puts promotions(:full).description_public_en.inspect
puts promotions(:full).description_public.inspect
```
yields nil for both.

So this is an issue (for which, admittedly Rails doc does not help).   
To which I might attempt a documentation PR... However, I still do not see how to resolve the Minitest fixture issue.

[Sorry for corss-posting, but since I realised , post facto, the issue was marked closed, it might not pop up]
_Originally posted by @dvodvo in https://github.com/shioyama/mobility/issues/626#issuecomment-2266446078_
